// Generated by gencpp from file vision/img.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_IMG_H
#define VISION_MESSAGE_IMG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct img_
{
  typedef img_<ContainerAllocator> Type;

  img_()
    : x(0)
    , y(0)
    , w(0)
    , h(0)
    , name()  {
    }
  img_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , w(0)
    , h(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _w_type;
  _w_type w;

   typedef int64_t _h_type;
  _h_type h;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::vision::img_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::img_<ContainerAllocator> const> ConstPtr;

}; // struct img_

typedef ::vision::img_<std::allocator<void> > img;

typedef boost::shared_ptr< ::vision::img > imgPtr;
typedef boost::shared_ptr< ::vision::img const> imgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::img_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::img_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision::img_<ContainerAllocator1> & lhs, const ::vision::img_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.w == rhs.w &&
    lhs.h == rhs.h &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision::img_<ContainerAllocator1> & lhs, const ::vision::img_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision::img_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::img_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::img_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::img_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::img_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::img_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::img_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e97835a549c09a8a2ee6344f1224772";
  }

  static const char* value(const ::vision::img_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e97835a549c09a8ULL;
  static const uint64_t static_value2 = 0xa2ee6344f1224772ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::img_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/img";
  }

  static const char* value(const ::vision::img_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::img_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n"
"int64 y\n"
"int64 w\n"
"int64 h\n"
"string name\n"
;
  }

  static const char* value(const ::vision::img_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::img_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
      stream.next(m.h);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct img_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::img_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::img_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "w: ";
    Printer<int64_t>::stream(s, indent + "  ", v.w);
    s << indent << "h: ";
    Printer<int64_t>::stream(s, indent + "  ", v.h);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_IMG_H
