// Generated by gencpp from file vision/img_list.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_IMG_LIST_H
#define VISION_MESSAGE_IMG_LIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vision/img.h>

namespace vision
{
template <class ContainerAllocator>
struct img_list_
{
  typedef img_list_<ContainerAllocator> Type;

  img_list_()
    : images()  {
    }
  img_list_(const ContainerAllocator& _alloc)
    : images(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::vision::img_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::vision::img_<ContainerAllocator> >> _images_type;
  _images_type images;





  typedef boost::shared_ptr< ::vision::img_list_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::img_list_<ContainerAllocator> const> ConstPtr;

}; // struct img_list_

typedef ::vision::img_list_<std::allocator<void> > img_list;

typedef boost::shared_ptr< ::vision::img_list > img_listPtr;
typedef boost::shared_ptr< ::vision::img_list const> img_listConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::img_list_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::img_list_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision::img_list_<ContainerAllocator1> & lhs, const ::vision::img_list_<ContainerAllocator2> & rhs)
{
  return lhs.images == rhs.images;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision::img_list_<ContainerAllocator1> & lhs, const ::vision::img_list_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision::img_list_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::img_list_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::img_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::img_list_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::img_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::img_list_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::img_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beeae6a30f35d07ad6b429e4f70ceea5";
  }

  static const char* value(const ::vision::img_list_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbeeae6a30f35d07aULL;
  static const uint64_t static_value2 = 0xd6b429e4f70ceea5ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::img_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/img_list";
  }

  static const char* value(const ::vision::img_list_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::img_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/img[] images\n"
"================================================================================\n"
"MSG: vision/img\n"
"int64 x\n"
"int64 y\n"
"int64 w\n"
"int64 h\n"
"string name\n"
;
  }

  static const char* value(const ::vision::img_list_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::img_list_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.images);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct img_list_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::img_list_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::img_list_<ContainerAllocator>& v)
  {
    s << indent << "images[]" << std::endl;
    for (size_t i = 0; i < v.images.size(); ++i)
    {
      s << indent << "  images[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vision::img_<ContainerAllocator> >::stream(s, indent + "    ", v.images[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_IMG_LIST_H
