// Generated by gencpp from file vision/PersonCountResponse.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_PERSONCOUNTRESPONSE_H
#define VISION_MESSAGE_PERSONCOUNTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct PersonCountResponse_
{
  typedef PersonCountResponse_<ContainerAllocator> Type;

  PersonCountResponse_()
    : count(0)  {
    }
  PersonCountResponse_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int64_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::vision::PersonCountResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::PersonCountResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PersonCountResponse_

typedef ::vision::PersonCountResponse_<std::allocator<void> > PersonCountResponse;

typedef boost::shared_ptr< ::vision::PersonCountResponse > PersonCountResponsePtr;
typedef boost::shared_ptr< ::vision::PersonCountResponse const> PersonCountResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::PersonCountResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::PersonCountResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision::PersonCountResponse_<ContainerAllocator1> & lhs, const ::vision::PersonCountResponse_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision::PersonCountResponse_<ContainerAllocator1> & lhs, const ::vision::PersonCountResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision::PersonCountResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::PersonCountResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::PersonCountResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::PersonCountResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::PersonCountResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::PersonCountResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::PersonCountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dbac33d2eb67bfeeedd516d65fec846";
  }

  static const char* value(const ::vision::PersonCountResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dbac33d2eb67bfeULL;
  static const uint64_t static_value2 = 0xeedd516d65fec846ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::PersonCountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/PersonCountResponse";
  }

  static const char* value(const ::vision::PersonCountResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::PersonCountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 count\n"
;
  }

  static const char* value(const ::vision::PersonCountResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::PersonCountResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonCountResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::PersonCountResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::PersonCountResponse_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int64_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_PERSONCOUNTRESPONSE_H
