(cl:defpackage vision-srv
  (:use )
  (:export
   "NEWHOST"
   "<NEWHOST-REQUEST>"
   "NEWHOST-REQUEST"
   "<NEWHOST-RESPONSE>"
   "NEWHOST-RESPONSE"
   "PERSONCOUNT"
   "<PERSONCOUNT-REQUEST>"
   "PERSONCOUNT-REQUEST"
   "<PERSONCOUNT-RESPONSE>"
   "PERSONCOUNT-RESPONSE"
   "TRACKPERSON"
   "<TRACKPERSON-REQUEST>"
   "TRACKPERSON-REQUEST"
   "<TRACKPERSON-RESPONSE>"
   "TRACKPERSON-RESPONSE"
  ))

