DG: false
FSGD: false
PCB: false
adv: 0.0
aiter: 10
arcface: false
batchsize: 32
circle: false
color_jitter: false
contrast: false
cosface: false
cosine: false
data_dir: DukeMTMC-reID/pytorch
droprate: 0.5
erasing_p: 0
fp16: false
gpu_ids:
- 0
ibn: false
ins_gamma: 32
instance: false
lifted: false
linear_num: 512
lr: 0.05
name: ft_net_dense
nclasses: 702
sphere: false
stride: 2
total_epoch: 60
train_all: false
triplet: false
use_NAS: false
use_convnext: false
use_dense: true
use_efficient: false
use_hr: false
use_swin: false
use_swinv2: false
warm_epoch: 0
weight_decay: 0.0005
